services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ciac_db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Ares4421096"
    ports:
      - "1433:1433"
    volumes:
      - ciac_sql_data:/var/opt/mssql

  api:
    build:
      context: ./CIAC-TAS-Service-API
      dockerfile: Dockerfile
    container_name: ciac_api
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=db;Database=CIAC_TAS;User Id=sa;Password=Ares4421096;TrustServerCertificate=True;Encrypt=False"
    ports:
      - "8080:8080"
    depends_on:
      - db

  web:
    build:
      context: ./CIAC-TAS-Web-FrontEnd
      dockerfile: Dockerfile
    container_name: ciac_web
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ApiSettings__BaseUrl: "http://api:8080"
    ports:
      - "8081:8081"
    depends_on:
      - api

volumes:
  ciac_sql_data:
