services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ciac_db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Ares4421096!"
    ports:
      - "1433:1433"
    volumes:
      - ciac_sql_data:/var/opt/mssql

  api:
    image: ciac-tas/api:1.0
    build:
      context: .
      dockerfile: CIAC-TAS-Service-API/CIAC-TAS-Service/Dockerfile
    container_name: ciac_api
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=db;Database=CIAC_TAS;User Id=sa;Password=Ares4421096!;TrustServerCertificate=True;Encrypt=False"
    ports:
      - "5001:5001"
    depends_on:
      - db

  web:
    image: ciac-tas/web:1.0
    build:
      context: .
      dockerfile: CIAC-TAS-Web-FrontEnd/CIAC-TAS-Web-FrontEnd/CIAC-TAS-Web-UI/Dockerfile
    container_name: ciac_web
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ServiceUrl: "http://api:5001"
      ApiSettings__BaseUrl: "http://api:5001"
    ports:
      - "8081:8081"
    depends_on:
      - api

volumes:
  ciac_sql_data:
